-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5fe82b3a37983b3270b7afa2ed80b90b158f3a7c
    hooks:
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E501']
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: git://github.com/asottile/reorder_python_imports
    sha: a46fdf085aaa9afc4ab68015f903ac6c824a5b42
    hooks:
    -   id: reorder-python-imports
